add tweet count logger to stream.py #14
kaustav202/RealTime-TwitterDataAnalysis pull request #23
Opened 2022-10-07 16:59 UTC by Coder-Manan

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the `CONTRIBUTING` guide.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
#14 

* **What is the new behavior (if this is a feature change)?**
Log no of tweets written to tweets.json after every thousand writes

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Test plan (required)**
No plan
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
```python
if (self.counter % 1000 == 0):
            print("No of tweets currently in tweets.json = ", self.counter)
```

**Code formatting**

**Closing issues**

Fixes #14

2022-10-07 18:11 UTC, Coder-Manan commented
Currently I am printing the number of tweets after every thousand writes

2022-10-07 18:49 UTC, kaustav202 requested changes
I'm not sure that prints anything to the terminal

2022-10-07 18:57 UTC, kaustav202 commented
Also add logging on smaller count like 50.. it takes a long time to reach 1000 tweets

2022-10-07 19:21 UTC, Coder-Manan commented
> Also add logging on smaller count like 50.. it takes a long time to reach 1000 tweets

Fixed it

2022-10-07 19:21 UTC, kaustav202 requested changes
not logging last i checked

2022-10-07 19:57 UTC, Coder-Manan commented
I am getting the following error when trying to run the app
```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\xxxx\xxxx\RealTime-TwitterDataAnalysis\app\main.py", line 29, in <module>
    python = check_word_in_tweet('#google', ds_tweets)
  File "D:\xxxx\xxxx\RealTime-TwitterDataAnalysis\app\main.py", line 16, in check_word_in_tweet
    contains_column = data['text'].str.contains(word, case = False)
  File "C:\Python310\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'text'
```

2022-10-08 02:59 UTC, kaustav202 commented
> I am getting the following error when trying to run the app
> 
> ```
> Traceback (most recent call last):
>   File "C:\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3800, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'text'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\xxxx\xxxx\RealTime-TwitterDataAnalysis\app\main.py", line 29, in <module>
>     python = check_word_in_tweet('#google', ds_tweets)
>   File "D:\xxxx\xxxx\RealTime-TwitterDataAnalysis\app\main.py", line 16, in check_word_in_tweet
>     contains_column = data['text'].str.contains(word, case = False)
>   File "C:\Python310\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "C:\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
>     raise KeyError(key) from err
> KeyError: 'text'
> ```

Check your tweets.json file.. most likely it has no data. you need to run stream.py and then run main after a gap

2022-10-08 03:00 UTC, kaustav202 commented
Also fetch the latest from upstream before proceeding

2022-10-08 09:29 UTC, Coder-Manan commented
Ok. I will look into it today

2022-10-08 11:34 UTC, Coder-Manan commented
Please check if logging is happening now or not, I have changed the location where I was printing the counter

2022-10-09 11:45 UTC, Coder-Manan commented
@kaustav202

2022-10-28 06:25 UTC, kaustav202 approved these changes
Works Fine

2022-10-28 06:25 UTC, kaustav202 commented on app/stream.py
> +                print("No of tweets currently in tweets.json = ", self.counter)
`print("Tweets loaded in tweets.json = ", self.counter)`

2022-10-28 06:25 UTC, kaustav202 commented on app/stream.py
> +        #     print("No of tweets currently in tweets.json = ", self.counter)
`
`

2022-10-28 06:29 UTC, merged